version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./src:/src
    php:
        image: php:8.0-fpm
        volumes:
            - ./src:/src